import {chromium} from 'playwright';
import assert from 'node:assert/strict';
const browser=await chromium.launch();const page=await browser.newPage({viewport:{width:375,height:812},isMobile:true,hasTouch:true});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto((process.env.AVAILABILITY_BASE_URL||'http://localhost:8033')+'/src/?demo=1');
await page.evaluate(async()=>{joinMeet('m1');await openRoom('m1');await aiPlan()});
await page.getByRole('button',{name:'가능 시간 조율',exact:true}).click();
await page.locator('#avstart').fill('2027-12-31');await page.locator('#avend').fill('2028-01-01');
await page.getByRole('button',{name:'범위 적용 · 응답 초기화'}).click();
const first=page.locator('.av-slot').nth(0);await first.scrollIntoViewIfNeeded();const a=await first.boundingBox(),b=await page.locator('.av-slot').nth(4).boundingBox();
const cdp=await page.context().newCDPSession(page);
async function stroke(){
await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:a.x+a.width/2,y:a.y+a.height/2}]});
for(let y=a.y+a.height/2;y<=b.y+b.height/2;y+=8)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:a.x+a.width/2,y}]});
await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
}
await stroke();
assert.equal(await page.locator('.av-slot[aria-pressed=true]').count(),3);
await stroke();
assert.equal(await page.locator('.av-slot[aria-pressed=true]').count(),0);
await stroke();
assert.equal(await page.locator('.av-slot[aria-pressed=true]').count(),3);
await page.getByRole('button',{name:'내 가능 시간 저장'}).click();
await page.locator('.av-slot').nth(1).focus();await page.keyboard.press('Space');
assert.equal(await page.locator('.av-slot[aria-pressed=true]').count(),4);
await page.getByRole('button',{name:'내 가능 시간 저장'}).click();
await page.locator('#avcandidates button').first().click();
await page.screenshot({path:'/tmp/availability-mobile.png'});
await page.getByRole('button',{name:'닫기',exact:true}).last().click();
await page.reload();await page.evaluate(async()=>{await openRoom('m1')});
await page.getByRole('button',{name:'가능 시간 조율',exact:true}).click();
assert.equal(await page.locator('.av-slot[aria-pressed=true]').count(),4);
assert.ok((await page.locator('#avcandidates').innerText()).includes('선택됨'));
await page.getByRole('button',{name:'닫기',exact:true}).last().click();
await page.getByRole('button',{name:'이 약속으로 확정',exact:true}).click();
await page.reload();await page.evaluate(()=>openRoom('m1'));
await page.getByRole('button',{name:'만남 완료',exact:true}).waitFor();
await page.reload();await page.evaluate(()=>openRoom('m1'));
await page.getByRole('button',{name:'만남 완료',exact:true}).waitFor();
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
assert.deepEqual(errors,[]);
console.log('모바일 검증 통과: 실제 터치 드래그, 키보드, 저장, 후보 선택, 새로고침 복원, 가로 넘침 없음');
await browser.close();
