import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql as $$select current_setting('test.uid',true)::uuid$$;
create table meetings(id uuid primary key,created_by uuid);
create table meeting_members(meeting_id uuid,user_id uuid,joined_at timestamptz);
create table meeting_plans(id uuid primary key,meeting_id uuid,created_by uuid,created_at timestamptz default now(),confirmed boolean default false,meet_at timestamptz,time_label text);
create table meeting_plan_votes(plan_id uuid,user_id uuid);
`);
await db.exec(fs.readFileSync(new URL('../../supabase/migrations/0012_plan_availability.sql',import.meta.url),'utf8'));
const host='00000000-0000-0000-0000-000000000001',guest='00000000-0000-0000-0000-000000000002', outsider='00000000-0000-0000-0000-000000000003',room='00000000-0000-0000-0000-000000000004',plan='00000000-0000-0000-0000-000000000005';
await db.exec(`insert into auth.users values ('${host}'),('${guest}'),('${outsider}');insert into meetings values('${room}','${host}');insert into meeting_members values('${room}','${host}',now()-interval '1 day'),('${room}','${guest}',now()-interval '1 day');insert into meeting_plans(id,meeting_id,created_by) values('${plan}','${room}','${host}')`);
const login=uid=>db.query("select set_config('test.uid',$1,false)",[uid]);
let revision=0;
async function write(action,payload){const r=await db.query('select update_plan_schedule($1,$2,$3) p',[plan,action,JSON.stringify({...payload,revision})]);revision=r.rows[0].p.schedule.revision;return r.rows[0].p;}
await login(guest);await assert.rejects(write('configure',{start:'2027-12-31',end:'2028-01-01',from:0,to:60}));
await login(host);await write('configure',{start:'2027-12-31',end:'2028-01-01',from:0,to:60});
await assert.rejects(db.query('insert into meeting_plan_votes values($1,$2)',[plan,host]));
const slot='2027-12-30T15:00:00.000Z',second='2027-12-30T15:30:00.000Z';
await write('save',{slots:[slot,second]});
await assert.rejects(db.query('select update_plan_schedule($1,$2,$3)',[plan,'save',JSON.stringify({slots:[slot],revision:0})]));
await login(guest);await write('save',{slots:[slot]});
await assert.rejects(write('save',{slots:['2027-12-30T14:30:00.000Z']}));
await assert.rejects(write('select',{slot}));
await login(outsider);await assert.rejects(write('save',{slots:[slot]}));
await login(host);await assert.rejects(write('select',{slot:second}));
const selected=await write('select',{slot});assert.equal(new Date(selected.meet_at).toISOString(),slot);
await db.query('insert into meeting_plan_votes values($1,$2)',[plan,host]);
await assert.rejects(write('configure',{start:'2028-01-01',end:'2028-01-01',from:0,to:60}));
await assert.rejects(write('save',{slots:[]}));
console.log('SQL 검증 통과: 권한, 슬롯 경계, 최다 후보, 시각 저장, 투표 잠금');
await db.close();
