import {chromium} from 'playwright';
import assert from 'node:assert/strict';
const browser=await chromium.launch();const page=await browser.newPage({viewport:{width:375,height:812},isMobile:true,hasTouch:true});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto((process.env.SCHEDULING_BASE_URL||'http://127.0.0.1:8047')+'/src/?demo=1');
await page.evaluate(async()=>{joinMeet('m1');await openRoom('m1');await aiPlan()});
await page.getByRole('button',{name:'장소 추천받고 시간표 열기'}).click();
await page.locator('.pollcell').first().waitFor();
await page.locator('.pollcell').first().scrollIntoViewIfNeeded();
const a=await page.locator('.pollcell[data-slot="0"]').boundingBox(),b=await page.locator('.pollcell[data-slot="10"]').boundingBox();
const cdp=await page.context().newCDPSession(page);
async function stroke(){
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:a.x+a.width/2,y:a.y+a.height/2}]});
 await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:b.x+b.width/2,y:b.y+b.height/2}]});
 await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
}
await stroke();assert.equal(await page.locator('.pollcell[aria-pressed=true]').count(),6);
await stroke();assert.equal(await page.locator('.pollcell[aria-pressed=true]').count(),0);
await page.locator('.pollcell').first().focus();await page.keyboard.press('Space');assert.equal(await page.locator('.pollcell[aria-pressed=true]').count(),1);
await page.locator('.pollcell').nth(1).focus();await page.keyboard.press('Space');
assert.equal(await page.locator('.pollcell[aria-pressed=true]').count(),2);
await page.screenshot({path:'/tmp/scheduling-mobile.png'});
await page.locator('input[name=pollCandidate]').first().check();
await page.getByRole('button',{name:'가능 시간과 장소 저장'}).click();
await page.getByText('제출 완료 · 마감 전까지 수정할 수 있어요',{exact:true}).waitFor();
const qid=await page.evaluate(()=>POLL.id);
await page.reload();await page.evaluate(id=>loadPoll(id),qid);
assert.equal(await page.locator('.pollcell[aria-pressed=true]').count(),2);
await page.getByRole('button',{name:'응답 비교 · 약속 확정'}).click();
await page.locator('input[name=finalCandidate]').first().check();
await page.locator('.pollcell').first().click();
assert.equal(await page.locator('#pollFinalSlot').inputValue(),'0');
await page.getByRole('button',{name:'선택한 장소와 시간으로 최종 확정'}).click();
await page.getByRole('button',{name:'이미 확정된 약속'}).waitFor();
await page.getByRole('button',{name:'채팅방에서 약속 보기'}).click();
await page.getByRole('button',{name:'만남 완료',exact:true}).waitFor();
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
assert.deepEqual(errors,[]);console.log('375×812 통과: 터치 직사각형 선택·해제, 키보드, 저장, 새로고침, 방장 확정, 채팅 복귀, 가로 넘침 없음');
await browser.close();
